#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,4,9,19,41,43,55&i=1,2,3,4,15,16,17,31,32,33&v=4,5,-1,22,27,26,25,35,32,33 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU
#define DSP_MODEL			DSP_ILI9341
#define BRIGHTNESS_PIN			22
#define ENC2_BTNR			35
#define ENC2_BTNL			32
#define ENC2_BTNB			33
#define ENC2_INTERNALPULLUP			false


#endif
